global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codesnap-monitor'

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s